#!/bin/sh
# ============================================================
# ABC Calculators — trivial build script
# Concatenates shared + tool-specific CSS/JS into one self-contained
# HTML fragment per tool, ready to paste directly into a ModX Chunk.
# No bundler, no npm — plain shell + cat, on purpose (see README).
# ============================================================
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
DIST="$ROOT/dist"
mkdir -p "$DIST"

build_tool() {
  tool_dir="$1"
  out_file="$2"

  {
    echo "<!-- ABC Calculators: $tool_dir — generated by build.sh, do not edit by hand -->"
    echo "<style>"
    cat "$ROOT/shared/styles/fonts.css"
    echo ""
    cat "$ROOT/shared/styles/base.css"
    echo ""
    cat "$ROOT/$tool_dir/calculator.css"
    echo "</style>"
    echo ""
    # Extract the calculator HTML between explicit markers in index.html
    # (not div-balance matching — too fragile in plain sed/awk).
    sed -n '/ABC-CALC-HTML-START/,/ABC-CALC-HTML-END/p' "$ROOT/$tool_dir/index.html" \
      | sed '1d;$d'
    echo ""
    echo "<script>"
    cat "$ROOT/shared/utils/format.js"
    echo ""
    cat "$ROOT/$tool_dir/calculator.js"
    echo "</script>"
  } > "$DIST/$out_file"

  echo "Built $DIST/$out_file"
}

build_tool "mbta-fare-calculator" "mbta-fare-chunk.html"
build_tool "bluebikes-membership-calculator" "bluebikes-chunk.html"

echo "Done. Paste dist/*.html directly into a ModX Chunk."
