#!/bin/sh
# ============================================================
# ABC Calculators — trivial build script
# Concatenates shared + tool-specific CSS/JS into one self-contained
# HTML fragment per tool, ready to paste directly into a ModX Chunk.
# No bundler, no npm — plain shell + cat, on purpose (see README).
# ============================================================
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
DIST="$ROOT/dist"
mkdir -p "$DIST"

build_tool() {
  tool_dir="$1"
  out_file="$2"

  {
    echo "<!-- ABC Calculators: $tool_dir — generated by build.sh, do not edit by hand -->"
    echo "<style>"
    cat "$ROOT/shared/styles/fonts.css"
    echo ""
    cat "$ROOT/shared/styles/base.css"
    echo ""
    cat "$ROOT/$tool_dir/calculator.css"
    echo "</style>"
    echo ""
    # Extract the calculator HTML between explicit markers in index.html
    # (not div-balance matching — too fragile in plain sed/awk).
    sed -n '/ABC-CALC-HTML-START/,/ABC-CALC-HTML-END/p' "$ROOT/$tool_dir/index.html" \
      | sed '1d;$d'
    echo ""
    echo "<script>"
    cat "$ROOT/shared/utils/format.js"
    echo ""
    cat "$ROOT/$tool_dir/calculator.js"
    echo "</script>"
  } > "$DIST/$out_file"

  echo "Built $DIST/$out_file"
}

build_tool "mbta-fare-calculator" "mbta-fare-chunk.html"
build_tool "bluebikes-membership-calculator" "bluebikes-chunk.html"

# Standalone iframe-embed pages: wraps the same chunk in a full <html> doc
# with no external dependencies, for CMSes (like ModX resource content
# fields) whose sanitizer strips inline <style>/<script> from pasted
# content. Point an <iframe src="..."> at the hosted version of this file
# instead of pasting the chunk directly.
build_embed() {
  tool_dir="$1"
  chunk_file="$2"
  out_file="$3"
  title="$4"

  {
    echo "<!doctype html>"
    echo "<!-- ABC Calculators: $tool_dir iframe-embed page — generated by build.sh, do not edit by hand -->"
    echo "<html lang=\"en\">"
    echo "<head>"
    echo "<meta charset=\"UTF-8\" />"
    echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
    echo "<title>$title</title>"
    echo "</head>"
    echo "<body style=\"margin:0;\">"
    cat "$DIST/$chunk_file"
    echo "</body>"
    echo "</html>"
  } > "$DIST/$out_file"

  echo "Built $DIST/$out_file"
}

build_embed "mbta-fare-calculator" "mbta-fare-chunk.html" "mbta-fare-embed.html" "MBTA Fare Calculator"
build_embed "bluebikes-membership-calculator" "bluebikes-chunk.html" "bluebikes-embed.html" "Bluebikes Membership Calculator"

echo "Done. Paste dist/*-chunk.html directly into a ModX Chunk, or point an"
echo "iframe at the hosted dist/*-embed.html page if Chunk access isn't available."
